apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
  namespace: vpn
data:
  config.json: |
    {
      "inbounds": [
        {
          "port": 443,
          "protocol": "vless",
          "settings": {
            "clients": [
              {
                "id": "ВАШ_UUID",    // Сюда вставить свой UUID!
                "flow": "xtls-rprx-vision"
              }
            ],
            "decryption": "none",
            "fallbacks": [
              { "dest": 80 }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "security": "tls",
            "tlsSettings": {
              "certificates": [
                {
                  "certificateFile": "/etc/v2ray-certs/cert.pem",
                  "keyFile": "/etc/v2ray-certs/key.pem"
                }
              ]
            },
            "wsSettings": {
              "path": "/"
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
