apiVersion: v1
kind: ConfigMap
metadata:
  name: dante-config
  namespace: vpn
data:
  sockd.conf: |
    logoutput: /dev/stdout
    internal: 0.0.0.0 port = 1080
    external: wgcf-profile
    method: none
    user.privileged: root
    user.unprivileged: nobody
    client pass {
      from: 0.0.0.0/0 to: 0.0.0.0/0
      log: connect disconnect error
    }
    pass {
      from: 0.0.0.0/0 to: 0.0.0.0/0
      protocol: tcp udp
      log: connect disconnect error
    }
