apiVersion: v1
kind: Service
metadata:
  name: warp-proxy-svc
  namespace: vpn
spec:
  type: NodePort
  selector:
    app: warp-proxy
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
      nodePort: 31080
