apiVersion: v1
kind: Service
metadata:
  name: v2ray-warp-svc
  namespace: vpn
spec:
  type: NodePort
  selector:
    app: v2ray-warp
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 31443
