apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-warp
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray-warp
  template:
    metadata:
      labels:
        app: v2ray-warp
    spec:
      containers:
      - name: warp
        image: fscarmen/warp
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: wgcf
          mountPath: /etc/wireguard
      - name: v2ray
        image: v2fly/v2fly-core
        args: ["run", "-c", "/etc/v2ray/config.json"]
        ports:
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/v2ray
        - name: certs
          mountPath: /etc/v2ray-certs
      volumes:
      - name: config
        configMap:
          name: v2ray-config
      - name: certs
        secret:
          secretName: v2ray-tls-secret
      - name: wgcf
        secret:
          secretName: warp-wg
