apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-proxy
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp-proxy
  template:
    metadata:
      labels:
        app: warp-proxy
    spec:
      containers:
        - name: wireguard
          image: ghcr.io/fscarmen/warp-for-docker
          env:
            - name: WARP_CONF
              value: /etc/wireguard/wgcf-profile.conf
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: wgcf
              mountPath: /etc/wireguard
        - name: dante
          image: looterz/dante
          ports:
            - containerPort: 1080
          volumeMounts:
            - name: dante-config
              mountPath: /etc/dante
      volumes:
        - name: wgcf
          secret:
            secretName: warp-wg
        - name: dante-config
          configMap:
            name: dante-config
