apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-proxy
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp-proxy
  template:
    metadata:
      labels:
        app: warp-proxy
    spec:
      containers:
      - name: wireguard-go
        image: masipcat/wireguard-go
        env:
          - name: WG_CONFIG
            value: /etc/wireguard/wgcf-profile.conf
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
          - name: wgcf
            mountPath: /etc/wireguard
      - name: socks5
        image: serjs/go-socks5-proxy
        args: ["-p", "1080"]
        ports:
          - containerPort: 1080
      volumes:
        - name: wgcf
          secret:
            secretName: warp-wg
